export const CHANGE_PARAMETER = 'CHANGE_PARAMETER';
export const DISMISS_ERROR = 'DISMISS_ERROR';
export const QUERY_RECORDS = 'QUERY_RECORDS';
export const RECEIVE_ERROR = 'RECEIVE_ERROR';
export const RECEIVE_RECORDS = 'RECEIVE_RECORDS';
export const SORT_RECORDS = 'SORT_RECORDS';
