export const CHANGE_FORM_FIELD = 'CHANGE_FORM_FIELD';
export const DISMISS_ERROR = 'DISMISS_ERROR';
export const RECEIVE_ERROR = 'RECEIVE_ERROR';
export const RECEIVE_FORM_DATA = 'RECEIVE_FORM_DATA';
export const RECEIVE_IMPORT_DATA_SUCCESS = 'RECEIVE_IMPORT_DATA_SUCCESS';
export const RECEIVE_REQUEST_FORM_DATA_ERROR =
  'RECEIVE_REQUEST_FORM_DATA_ERROR';
export const RECEIVE_REQUEST_TABLE_RECORDS_ERROR =
  'RECEIVE_REQUEST_TABLE_RECORDS_ERROR';
export const RECEIVE_TABLE_RECORDS = 'RECEIVE_TABLE_RECORDS';
export const REQUEST_FORM_DATA = 'REQUEST_FORM_DATA';
export const REQUEST_TABLE_RECORDS = 'REQUEST_TABLE_RECORDS';
export const RESET_FORM_FIELDS = 'RESET_FORM_FIELDS';
export const SORT_TABLE_RECORDS = 'SORT_TABLE_RECORDS';
